### ISSUE TITLE
Possible Bug: Incompatible with AppCompatDelegate.setDefaultNightMode

### ISSUE THREAD

**Issue by DeweyReed** [googlearchive/android-PictureInPicture#14]
1. Set night theme before super.onCreate

	```Java
	@Override
	protected void onCreate(Bundle savedInstanceState) {
	    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
	    super.onCreate(savedInstanceState);
	    setContentView(R.layout.activity_main);
	```
	

1. Change activity theme to DayNight

	`<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">`

1. After starting app, everything looks fine. But when click "enter pip mode" button, the video is stopped and restarted from the beginning. It seems the whole activity is recreated in the night mode so the playing is discontinued. This doesn't happen in the day mode.

I've observed this bug on emulators and devices using support library or androidX.

**Comment by Angels-group** [comment]
I have a similar problem.
If the night theme is turned on in activity - and enter PiP mode - a graphical bug appears.

![image](https://user-images.githubusercontent.com/1552042/54609200-84b23500-4a63-11e9-8c3d-135698546ef3.png)

if i use DAY mode - all ok

![image](https://user-images.githubusercontent.com/1552042/54609270-aad7d500-4a63-11e9-8271-7e4d998db876.png)

Night mode is enabled "globally" in the class extending Application

**Comment by Angels-group** [comment]
**UPD:**
Switch to alpha version

` implementation 'androidx.appcompat:appcompat:1.1.0-alpha03' `

fix this issue.

**Comment by DeweyReed** [comment]
> **UPD:**
> Switch to alpha version
> 
> `implementation 'androidx.appcompat:appcompat:1.1.0-alpha03'`
> 
> fix this issue.

Thanks you. It works like a charm.
